import type { Stock } from "@/domain/entities/Stock";

export const DAX40_MARKET_ID = "dax40";

export const dax40Stocks: Stock[] = [
  {marketId: DAX40_MARKET_ID, ticker: "^GDAXI", name: "DAX", tradingViewSymbol: "XETR:DAX"},
  {marketId: DAX40_MARKET_ID, ticker: "SAP", name: "SAP", tradingViewSymbol: "XETR:SAP"},
  {marketId: DAX40_MARKET_ID, ticker: "SIE", name: "Siemens", tradingViewSymbol: "XETR:SIE"},
  {marketId: DAX40_MARKET_ID, ticker: "ALV", name: "Allianz", tradingViewSymbol: "XETR:ALV"},
  {marketId: DAX40_MARKET_ID, ticker: "DTE", name: "Deutsche Telekom", tradingViewSymbol: "XETR:DTE"},
  {marketId: DAX40_MARKET_ID, ticker: "BMW", name: "BMW", tradingViewSymbol: "XETR:BMW"},
  {marketId: DAX40_MARKET_ID, ticker: "MBG", name: "Mercedes-Benz Group", tradingViewSymbol: "XETR:MBG"},
  {marketId: DAX40_MARKET_ID, ticker: "VOW3", name: "Volkswagen", tradingViewSymbol: "XETR:VOW3"},
  {marketId: DAX40_MARKET_ID, ticker: "BAS", name: "BASF", tradingViewSymbol: "XETR:BAS"},
  {marketId: DAX40_MARKET_ID, ticker: "BAYN", name: "Bayer", tradingViewSymbol: "XETR:BAYN"},
  {marketId: DAX40_MARKET_ID, ticker: "DHL", name: "Deutsche Post", tradingViewSymbol: "XETR:DHL"},
  {marketId: DAX40_MARKET_ID, ticker: "ADS", name: "Adidas", tradingViewSymbol: "XETR:ADS"},
  {marketId: DAX40_MARKET_ID, ticker: "MUV2", name: "Munich Re", tradingViewSymbol: "XETR:MUV2"},
  {marketId: DAX40_MARKET_ID, ticker: "RWE", name: "RWE", tradingViewSymbol: "XETR:RWE"},
  {marketId: DAX40_MARKET_ID, ticker: "EOAN", name: "E.ON", tradingViewSymbol: "XETR:EOAN"},
  {marketId: DAX40_MARKET_ID, ticker: "IFX", name: "Infineon Technologies", tradingViewSymbol: "XETR:IFX"},
  {marketId: DAX40_MARKET_ID, ticker: "LIN", name: "Linde", tradingViewSymbol: "XETR:LIN"},
  {marketId: DAX40_MARKET_ID, ticker: "HEN3", name: "Henkel", tradingViewSymbol: "XETR:HEN3"},
  {marketId: DAX40_MARKET_ID, ticker: "FRE", name: "Fresenius", tradingViewSymbol: "XETR:FRE"},
  {marketId: DAX40_MARKET_ID, ticker: "CON", name: "Continental", tradingViewSymbol: "XETR:CON"},
  {marketId: DAX40_MARKET_ID, ticker: "BEI", name: "Beiersdorf", tradingViewSymbol: "XETR:BEI"},
  {marketId: DAX40_MARKET_ID, ticker: "MRK", name: "Merck KGaA", tradingViewSymbol: "XETR:MRK"},
  {marketId: DAX40_MARKET_ID, ticker: "MTX", name: "MTU Aero Engines", tradingViewSymbol: "XETR:MTX"},
  {marketId: DAX40_MARKET_ID, ticker: "BNR", name: "Brenntag", tradingViewSymbol: "XETR:BNR"},
  {marketId: DAX40_MARKET_ID, ticker: "1COV", name: "Covestro", tradingViewSymbol: "XETR:1COV"},
  {marketId: DAX40_MARKET_ID, ticker: "DB1", name: "Deutsche Börse", tradingViewSymbol: "XETR:DB1"},
  {marketId: DAX40_MARKET_ID, ticker: "DBK", name: "Deutsche Bank", tradingViewSymbol: "XETR:DBK"},
  {marketId: DAX40_MARKET_ID, ticker: "CBK", name: "Commerzbank", tradingViewSymbol: "XETR:CBK"},
  {marketId: DAX40_MARKET_ID, ticker: "HNR1", name: "Hannover Re", tradingViewSymbol: "XETR:HNR1"},
  {marketId: DAX40_MARKET_ID, ticker: "VNA", name: "Vonovia", tradingViewSymbol: "XETR:VNA"},
  {marketId: DAX40_MARKET_ID, ticker: "HEI", name: "Heidelberg Materials", tradingViewSymbol: "XETR:HEI"},
  {marketId: DAX40_MARKET_ID, ticker: "RHM", name: "Rheinmetall", tradingViewSymbol: "XETR:RHM"},
  {marketId: DAX40_MARKET_ID, ticker: "P911", name: "Porsche", tradingViewSymbol: "XETR:P911"},
  {marketId: DAX40_MARKET_ID, ticker: "AIR", name: "Airbus", tradingViewSymbol: "XETR:AIR"},
  {marketId: DAX40_MARKET_ID, ticker: "SRT3", name: "Sartorius", tradingViewSymbol: "XETR:SRT3"},
  {marketId: DAX40_MARKET_ID, ticker: "SY1", name: "Symrise", tradingViewSymbol: "XETR:SY1"},
  {marketId: DAX40_MARKET_ID, ticker: "ZAL", name: "Zalando", tradingViewSymbol: "XETR:ZAL"},
  {marketId: DAX40_MARKET_ID, ticker: "QIA", name: "Qiagen", tradingViewSymbol: "XETR:QIA"},
  {marketId: DAX40_MARKET_ID, ticker: "PUM", name: "Puma", tradingViewSymbol: "XETR:PUM"},
  {marketId: DAX40_MARKET_ID, ticker: "HFG", name: "HelloFresh", tradingViewSymbol: "XETR:HFG"},
  {marketId: DAX40_MARKET_ID, ticker: "DHER", name: "Delivery Hero", tradingViewSymbol: "XETR:DHER"}
];
