import type { Stock } from "@/domain/entities/Stock";

export const FTSE_MIB40_MARKET_ID = "ftse_mib40";

export const ftse_mib40Stocks: Stock[] = [
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "FTSEMIB",   name: "FTSE MIB",           tradingViewSymbol: "INDEX:FTSEMIB"  },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "ENI",       name: "Eni",                 tradingViewSymbol: "MIL:ENI"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "ENEL",      name: "Enel",                tradingViewSymbol: "MIL:ENEL"       },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "ISP",       name: "Intesa Sanpaolo",     tradingViewSymbol: "MIL:ISP"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "UCG",       name: "UniCredit",           tradingViewSymbol: "MIL:UCG"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "STM",       name: "STMicroelectronics",  tradingViewSymbol: "MIL:STM"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "STLAM",     name: "Stellantis",          tradingViewSymbol: "MIL:STLAM"      },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "RACE",      name: "Ferrari",             tradingViewSymbol: "MIL:RACE"       },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "G",         name: "Generali",            tradingViewSymbol: "MIL:G"          },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "MB",        name: "Mediobanca",          tradingViewSymbol: "MIL:MB"         },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "TIT",       name: "Telecom Italia",      tradingViewSymbol: "MIL:TIT"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "A2A",       name: "A2A",                 tradingViewSymbol: "MIL:A2A"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "AMP",       name: "Amplifon",            tradingViewSymbol: "MIL:AMP"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "ATL",       name: "Atlantia",            tradingViewSymbol: "MIL:ATL"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "AZM",       name: "Azimut Holding",      tradingViewSymbol: "MIL:AZM"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "BAMI",      name: "Banco BPM",           tradingViewSymbol: "MIL:BAMI"       },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "BMED",      name: "Banca Mediolanum",    tradingViewSymbol: "MIL:BMED"       },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "BPE",       name: "BPER Banca",          tradingViewSymbol: "MIL:BPE"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "BUZZI",     name: "Buzzi",               tradingViewSymbol: "MIL:BZU"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "CPR",       name: "Campari",             tradingViewSymbol: "MIL:CPR"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "CNHI",      name: "CNH Industrial",      tradingViewSymbol: "MIL:CNHI"       },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "DIA",       name: "DiaSorin",            tradingViewSymbol: "MIL:DIA"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "ERG",       name: "ERG",                 tradingViewSymbol: "MIL:ERG"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "FBK",       name: "FinecoBank",          tradingViewSymbol: "MIL:FBK"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "HER",       name: "Hera",                tradingViewSymbol: "MIL:HER"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "IG",        name: "Italgas",             tradingViewSymbol: "MIL:IG"         },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "INW",       name: "Inwit",               tradingViewSymbol: "MIL:INW"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "LDO",       name: "Leonardo",            tradingViewSymbol: "MIL:LDO"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "MONC",      name: "Moncler",             tradingViewSymbol: "MIL:MONC"       },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "NEXI",      name: "Nexi",                tradingViewSymbol: "MIL:NEXI"       },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "ORN",       name: "Terna",               tradingViewSymbol: "MIL:TRN"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "PIRC",      name: "Pirelli",             tradingViewSymbol: "MIL:PIRC"       },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "PRYSMIAN",  name: "Prysmian",            tradingViewSymbol: "MIL:PRY"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "REC",       name: "Recordati",           tradingViewSymbol: "MIL:REC"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "SPM",       name: "Saipem",              tradingViewSymbol: "MIL:SPM"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "SRG",       name: "Snam",                tradingViewSymbol: "MIL:SRG"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "TLIT",      name: "TIM",                 tradingViewSymbol: "MIL:TIM"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "UNI",       name: "Unipol",              tradingViewSymbol: "MIL:UNI"        },
  { marketId: FTSE_MIB40_MARKET_ID, ticker: "WBC",       name: "Webuild",             tradingViewSymbol: "MIL:WBC"        }
];
